# Generated by Django 4.2.1 on 2023-06-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
