# Generated by Django 4.2.1 on 2023-06-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_nome_birthday_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='dinner',
        ),
    ]
